apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
nodeStatusUpdateFrequency: 10s
cgroupDriver: "systemd"
evictionHard:
  memory.available: "200Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
containerRuntimeEndpoint: "unix:///run/crio/crio.sock"
cniConfDir: "/etc/cni/net.d"
cniBinDir: "/opt/cni/bin"
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
tlsCertFile: "/etc/kubernetes/pki/kubelet.crt"
tlsPrivateKeyFile: "/etc/kubernetes/pki/kubelet.key"
staticPodPath: "/etc/kubernetes/manifests"
eventRecordQPS: 5
logging:
  verbosity: 2
resolvConf: "/run/systemd/resolve/resolv.conf"
topologyManagerPolicy: "best-effort"
